version: '3.9'

services:
  backend:
    build: .
    container_name: fastapi-backend
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - REDIS_URL=redis://redis:6379/0

  db:
    image: postgres:13
    container_name: fastapi-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: fastapi-redis
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: fastapi-celery
    command: celery -A config.celery_app worker --loglevel=info
    depends_on:
      - backend
      - redis
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - REDIS_URL=redis://redis:6379/0

volumes:
  pgdata:
