"""Added Rest of the models

Revision ID: 0c47a2347fad
Revises: 236a1d62c66f
Create Date: 2025-06-15 01:47:04.311223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c47a2347fad'
down_revision: Union[str, None] = '236a1d62c66f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aggregated_summaries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('computed_result', sa.Float(), nullable=False),
    sa.Column('aggregation_type', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', name='aggregationtype'), nullable=False),
    sa.Column('aggregated_entity', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aggregated_summaries_id'), 'aggregated_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_aggregated_summaries_user_id'), 'aggregated_summaries', ['user_id'], unique=False)
    op.create_table('report_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('report_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_jobs_id'), 'report_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_report_jobs_user_id'), 'report_jobs', ['user_id'], unique=False)
    op.create_table('usage_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('usage_type', sa.String(), nullable=False),
    sa.Column('usage_amount', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_events_id'), 'usage_events', ['id'], unique=False)
    op.create_index(op.f('ix_usage_events_user_id'), 'usage_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_events_user_id'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_id'), table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_index(op.f('ix_report_jobs_user_id'), table_name='report_jobs')
    op.drop_index(op.f('ix_report_jobs_id'), table_name='report_jobs')
    op.drop_table('report_jobs')
    op.drop_index(op.f('ix_aggregated_summaries_user_id'), table_name='aggregated_summaries')
    op.drop_index(op.f('ix_aggregated_summaries_id'), table_name='aggregated_summaries')
    op.drop_table('aggregated_summaries')
    # ### end Alembic commands ###
