"""Added Usage event field

Revision ID: 14380c91d55b
Revises: 0c47a2347fad
Create Date: 2025-06-15 15:59:20.188288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14380c91d55b'
down_revision: Union[str, None] = '0c47a2347fad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_events', sa.Column('usage_unit', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usage_events', 'usage_unit')
    # ### end Alembic commands ###
