"""Updated models

Revision ID: 43060a8e0bfb
Revises: 14380c91d55b
Create Date: 2025-06-25 16:12:41.288946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43060a8e0bfb'
down_revision: Union[str, None] = '14380c91d55b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.execute("""
    #     ALTER TABLE aggregated_summaries
    #     ALTER COLUMN id TYPE INTEGER USING id::integer
    # """)
    # op.drop_index('ix_aggregated_summaries_id', table_name='aggregated_summaries')
    # op.alter_column('report_jobs', 'id',
    #            existing_type=sa.VARCHAR(),
    #            type_=sa.Integer(),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.drop_index('ix_report_jobs_id', table_name='report_jobs')
    op.drop_index('ix_usage_events_id', table_name='usage_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_usage_events_id', 'usage_events', ['id'], unique=False)
    # op.create_index('ix_report_jobs_id', 'report_jobs', ['id'], unique=False)
    # op.alter_column('report_jobs', 'id',
    #            existing_type=sa.Integer(),
    #            type_=sa.VARCHAR(),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.create_index('ix_aggregated_summaries_id', 'aggregated_summaries', ['id'], unique=False)
    # op.alter_column('aggregated_summaries', 'id',
    #            existing_type=sa.Integer(),
    #            type_=sa.VARCHAR(),
    #            existing_nullable=False,
    #            autoincrement=True)
    # ### end Alembic commands ###
