"""Updated models

Revision ID: 6a8fbf19fbcf
Revises: 43060a8e0bfb
Create Date: 2025-06-25 16:18:46.312435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a8fbf19fbcf'
down_revision: Union[str, None] = '43060a8e0bfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aggregated_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('computed_result', sa.Float(), nullable=False),
    sa.Column('aggregation_type', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', name='aggregationtype'), nullable=False),
    sa.Column('aggregated_entity', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aggregated_summaries_user_id'), 'aggregated_summaries', ['user_id'], unique=False)
    op.create_table('report_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('report_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_jobs_user_id'), 'report_jobs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_jobs_user_id'), table_name='report_jobs')
    op.drop_table('report_jobs')
    op.drop_index(op.f('ix_aggregated_summaries_user_id'), table_name='aggregated_summaries')
    op.drop_table('aggregated_summaries')
    # ### end Alembic commands ###
