name: Run Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL_SYNC: postgresql+psycopg2://test_user:test_pass@localhost:5432/test_db
      DATABASE_URL: postgresql+asyncpg://test_user:test_pass@localhost:5432/test_db
      SECRET_KEY: random
      EMAIL_HOST: random
      EMAIL_HOST_USER: random
      EMAIL_HOST_PASSWORD: random
      EMAIL_PORT: 587

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest tests.py
